<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodoHistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoHistRepository extends EntityRepository
{
}
