app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_crud_all:
    resource: "@AppBundle/Resources/config/routing.yml"
