arqueologo_index:
    path:     /
    defaults: { _controller: "AppBundle:Arqueologo:index" }
    methods:  GET

arqueologo_show:
    path:     /{id}/show/
    defaults: { _controller: "AppBundle:Arqueologo:show" }
    methods:  GET

arqueologo_new:
    path:     /new/
    defaults: { _controller: "AppBundle:Arqueologo:new" }
    methods:  [GET, POST]

arqueologo_edit:
    path:     /{id}/edit/
    defaults: { _controller: "AppBundle:Arqueologo:edit" }
    methods:  [GET, POST]

arqueologo_delete:
    path:     /{id}/delete/
    defaults: { _controller: "AppBundle:Arqueologo:delete" }
    methods:  DELETE
