municipio_index:
    path:     /
    defaults: { _controller: "AppBundle:Municipio:index" }
    methods:  GET

municipio_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Municipio:show" }
    methods:  GET

municipio_new:
    path:     /new
    defaults: { _controller: "AppBundle:Municipio:new" }
    methods:  [GET, POST]

municipio_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Municipio:edit" }
    methods:  [GET, POST]

municipio_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Municipio:delete" }
    methods:  DELETE
