app_epoca:
    resource: "@AppBundle/Resources/config/routing/epoca.yml"
    prefix:   /epoca

app_minicipio:
    resource: "@AppBundle/Resources/config/routing/Municipio.yml"
    prefix:   /municipio

app_provincia:
    resource: "@AppBundle/Resources/config/routing/provincia.yml"
    prefix:   /provincia

app_arqueologo:
    resource: "@AppBundle/Resources/config/routing/arqueologo.yml"
    prefix:   /arqueologo

app_yacimiento:
    resource: "@AppBundle/Resources/config/routing/yacimiento.yml"
    prefix:   /yacimiento